name: build-deno

# https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  release:
    types: [created]

# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobs
jobs:
  release_metadata:
    name: Get Release Upload URL
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.get_upload_url.outputs.upload_url }}
      test: ${{ steps.get_upload_url.outputs.test }}
    steps:
      - name: get_upload_url
        run: |
          response=$(curl -s -H "Accept: application/json" https://api.github.com/repos/lukechannings/docker-deno/releases)
          url=$(echo $response | jq -r ".[]|select(.tag_name==\"${GITHUB_REF#refs/tags/}\").upload_url")
          echo "::set-output name=test::hello"
          echo "::set-output name=upload_url::${url}"
  compile:
    runs-on: ubuntu-latest
    needs: release_metadata
    steps:
      - run: |
          echo ${{ needs.release_metadata.outputs.upload_url }}
          echo ${{ needs.release_metadata.outputs.test }}

